### ISSUE TITLE
`make dist` is broken due to deprecated use of `pypandoc`

### ISSUE THREAD

**Issue by radrow** [ethereum/pyrlp#137]
```
python setup.py sdist
/usr/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
Traceback (most recent call last):
  File "/home/radek/pyrlp/setup.py", line 44, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 476, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 900, in finalize_options
    ep(self)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/radek/pyrlp/.eggs/setuptools_markdown-0.4.1-py3.10.egg/setuptools_markdown.py", line 43, in long_description_markdown_filename
    output = pypandoc.convert(markdown_filename, 'rst', format='md')
AttributeError: module 'pypandoc' has no attribute 'convert'
make: *** [Makefile:70: dist] Error 1
```

I think the error message is pretty self-explanatory. `pypandoc` no longer exports `convert`, this issue is quite common among different ETH-related packages...

**Comment by pacrob** [comment]
Build and release process has been updated, uses `build` now, no more `pypandoc`.
