### ISSUE TITLE
pip install --no-binary :all: rlp 

### ISSUE THREAD

**Issue by vrypan** [ethereum/pyrlp#147]
### What happened?

The command `pip install --no-binary :all: rlp` fails with error.

### Code that produced the error

```python
pip install --no-binary :all: rlp
Collecting rlp
  Using cached rlp-3.0.0.tar.gz (40 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      long_description_markdown_filename: dist = <setuptools.dist.Distribution object at 0x103f75c50>; attr = 'long_description_markdown_filename'; value = 'README.md'
      Traceback (most recent call last):
        File "/Users/vrypan/Downloads/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/vrypan/Downloads/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/vrypan/Downloads/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 44, in <module>
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 680, in finalize_options
          ep(self)
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 700, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/normal/lib/python3.11/site-packages/setuptools_markdown.py", line 38, in long_description_markdown_filename
          frame = _get_code_object()
                  ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/1x/s5qfp7sn3rj5qmx_nkz1nx9m0000gn/T/pip-build-env-g80p3wct/normal/lib/python3.11/site-packages/setuptools_markdown.py", line 58, in _get_code_object
          code = frame.f_back.f_code
                 ^^^^^^^^^^^^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'f_code'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Fill this section in if you know how this could or should be fixed

I think that the problem is actually in the README.md file: 

Between "Snake" and "Charmers" there is a 0x0A (LF) character instead of 0x20 (SPACE). 

#146 May fix the problem.

### Python Version

3.11.6

### Operating System

osx

**Comment by fselmo** [comment]
I believe this has been taken care of by #146. Please ask to re-open if that's not the case.
