### ISSUE TITLE
ImportError: cannot import name str_to_bytes

### ISSUE THREAD

**Issue by pltrdy** [ethereum/pyrlp#19]
Hi,

I'm looking to use [pyethapp](https://github.com/ethereum/pyethapp) so i've installed pyrlp.

When running `pyethapp` I face a RLP related error which trace is:
`Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 7, in <module>
    from pyethapp.app import app
  File "/usr/local/lib/python2.7/dist-packages/pyethapp/app.py", line 11, in <module>
    import ethereum.slogging as slogging
  File "/usr/local/lib/python2.7/dist-packages/ethereum-1.2.0-py2.7.egg/ethereum/slogging.py", line 4, in <module>
    from ethereum.utils import bcolors, isnumeric
  File "/usr/local/lib/python2.7/dist-packages/ethereum-1.2.0-py2.7.egg/ethereum/utils.py", line 9, in <module>
    import rlp
  File "/usr/local/lib/python2.7/dist-packages/rlp/__init__.py", line 1, in <module>
    from . import sedes
  File "/usr/local/lib/python2.7/dist-packages/rlp/sedes/__init__.py", line 2, in <module>
    from .binary import Binary, binary
  File "/usr/local/lib/python2.7/dist-packages/rlp/sedes/binary.py", line 3, in <module>
    from ..utils import Atomic, str_to_bytes, bytes_to_str
ImportError: cannot import name str_to_bytes`

Any ideas?

**Comment by pltrdy** [comment]
don't know how but it looks like if failed the cloning
It was not uptodate (even if git pull was saying the opposite) rm -rf 'ed then clone again, its ok now

**Comment by pipermerriam** [comment]
Closing.  This seems like an error in userland.
